<?xml version="1.0" encoding="utf-8"?><Database Name="SAP_DB" Class="AlmacenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVOL340;Initial Catalog=SAP_DB;Integrated Security=True" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="SAP_DBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_ConsultaAlmacen" Method="sp_ConsultaAlmacen">
    <ElementType Name="sp_ConsultaAlmacenResult">
      <Column Name="Id_A" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertayModificaAlmacen" Method="sp_InsertayModificaAlmacen">
    <Parameter Name="id_a" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id_p" Parameter="id_p" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_EliminarDeAlmacen" Method="sp_EliminarDeAlmacen">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ConsultaStock" Method="sp_ConsultaStock">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ConsultaStockResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ReduceStock" Method="sp_ReduceStock">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ReduceStockResult">
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>