<?xml version="1.0" encoding="utf-8"?><Database Name="SAP_DB" Class="EmpleadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVOL340;Initial Catalog=SAP_DB;Integrated Security=True" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="SAP_DBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_EliminarEmpleado" Method="sp_EliminarEmpleado">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertayModificaEmpleados" Method="sp_InsertayModificaEmpleados">
    <Parameter Name="Id_emp" Parameter="id_emp" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Genero" Parameter="genero" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Foto" Parameter="foto" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="F_Nac" Parameter="f_Nac" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Puesto" Parameter="puesto" Type="System.String" DbType="NChar(30)" />
    <Parameter Name="Activo" Parameter="activo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ConsultaEmpleados" Method="sp_ConsultaEmpleados">
    <ElementType Name="sp_ConsultaEmpleadosResult">
      <Column Name="Id_emp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Foto" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="F_Nac" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Puesto" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ConsultaEmpleadosSinUsuario" Method="sp_ConsultaEmpleadosSinUsuario">
    <ElementType Name="sp_ConsultaEmpleadosSinUsuarioResult">
      <Column Name="Id_emp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>