#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAP_DB")]
	public partial class EmpleadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public EmpleadosDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.SAP_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmpleadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpleadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpleadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpleadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_EliminarEmpleado")]
		public int sp_EliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertayModificaEmpleados")]
		public int sp_InsertayModificaEmpleados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_emp", DbType="Int")] System.Nullable<int> id_emp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Genero", DbType="VarChar(20)")] string genero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="NVarChar(MAX)")] string foto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="F_Nac", DbType="DateTime")] System.Nullable<System.DateTime> f_Nac, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Puesto", DbType="NChar(30)")] string puesto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Bit")] System.Nullable<bool> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_emp, nombre, genero, foto, f_Nac, puesto, activo, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ConsultaEmpleados")]
		public ISingleResult<sp_ConsultaEmpleadosResult> sp_ConsultaEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ConsultaEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_ConsultaEmpleadosSinUsuario")]
		public ISingleResult<sp_ConsultaEmpleadosSinUsuarioResult> sp_ConsultaEmpleadosSinUsuario()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_ConsultaEmpleadosSinUsuarioResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_ConsultaEmpleadosResult
	{
		
		private int _Id_emp;
		
		private string _Nombre;
		
		private string _Genero;
		
		private string _Foto;
		
		private System.Nullable<System.DateTime> _F_Nac;
		
		private string _Puesto;
		
		private bool _Activo;
		
		private System.DateTime _Fecha;
		
		public sp_ConsultaEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_emp", DbType="Int NOT NULL")]
		public int Id_emp
		{
			get
			{
				return this._Id_emp;
			}
			set
			{
				if ((this._Id_emp != value))
				{
					this._Id_emp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(20)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this._Genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="NVarChar(MAX)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this._Foto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Nac", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_Nac
		{
			get
			{
				return this._F_Nac;
			}
			set
			{
				if ((this._F_Nac != value))
				{
					this._F_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puesto", DbType="NChar(30)")]
		public string Puesto
		{
			get
			{
				return this._Puesto;
			}
			set
			{
				if ((this._Puesto != value))
				{
					this._Puesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class sp_ConsultaEmpleadosSinUsuarioResult
	{
		
		private int _Id_emp;
		
		private string _Nombre;
		
		public sp_ConsultaEmpleadosSinUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_emp", DbType="Int NOT NULL")]
		public int Id_emp
		{
			get
			{
				return this._Id_emp;
			}
			set
			{
				if ((this._Id_emp != value))
				{
					this._Id_emp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
